### ISSUE TITLE
Add home page

### ISSUE THREAD

**Issue by Abid-Chowdhury** [Abid-Chowdhury/Habit-Quest#13]

**Comment by SininAssets** [comment]
![ConceptArt](https://github.com/Abid-Chowdhury/Habit-Quest/assets/144292292/5759bc53-0013-4303-a80b-ab9a0f956044)

Here is the Home Page Concept

**Comment by Abid-Chowdhury** [comment]
Implement this in HTML / CSS

**Comment by Abid-Chowdhury** [comment]
**Notes:**
- Add padding to edges
- Add photo background
- Add variables for colors in CSS page
- Import font instead of linking in HTML 
- Add dropshadow to elements
- Header spacing needs to be justified correctly
- Change HTML code formatting
- Comment out calender code
- Add day | time | date to main banner

**Comment by SininAssets** [comment]
3/25/2024

-Add padding to edges
-Add photo background(Pushed for later)
-Add variables for colors in CSS page (Complete)
-Import font instead of linking in HTML(Complete)
-Add dropshadow to elements
-Header spacing needs to be justified correctly
-Change HTML code formatting
-Comment out calender code(Complete)
-Add day | time | date to main banner (Complete)

**Comment by SininAssets** [comment]
3/27/2024
-Add padding to edges (Need to be discussed)
-add dropshadow to elements(Need clarifications)
-header spacing needs to be justified correctly (Need to be evaluated)
-Change HTML code formatting(Need to be evaluated)

**Comment by Abid-Chowdhury** [comment]
**3/28/2024**

- **Add padding to edges (Need to be discussed):**
Padding needs to be adjusted for all elements, and elements should not be touching the edge of the page or a box. **(See image 1)**

- **Add dropshadow to elements (Need clarifications):**
For texts, add the `text-shadow` property. For other elements, add `box-shadow` property. This will make the page look less flat and make text more readable.

- **Header spacing needs to be justified correctly (Need to be evaluated):**
Title text should be in one line (Give `h1` more width) **(See image 2)**

- **Change HTML code formatting (Need to be evaluated):**
Header should have 3 children divs (`left`, `middle`, `right`).
`left` div can be the title.
`middle` div can be all page buttons.
`right` div can be streak, coins, and profile icon.
For `mainclass` div, children divs should be written in order they appear on the page.

**Image 1**
![image](https://github.com/Abid-Chowdhury/Habit-Quest/assets/58383484/1d0932a8-ddbf-4c5f-9c5f-ca04487e9a5a)

**Image 2**
![image](https://github.com/Abid-Chowdhury/Habit-Quest/assets/58383484/3e760f33-8146-424b-8f8a-8b3afdd97b2b)
