### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by Abid-Chowdhury** [Abid-Chowdhury/Habit-Quest#27]
Add description of website and created by section. Need design from @SininAssets

**Comment by SininAssets** [comment]
![image](https://github.com/Abid-Chowdhury/Habit-Quest/assets/144292292/3c81f831-fccd-4184-8c83-4a2f9330b3c9)

**Comment by Abid-Chowdhury** [comment]
![image](https://github.com/Abid-Chowdhury/Habit-Quest/assets/58383484/84f59dfc-72a3-404f-b625-7b582a2a2818)
Heres what it looks like so far

**Comment by Abid-Chowdhury** [comment]
![image](https://github.com/Abid-Chowdhury/Habit-Quest/assets/58383484/c65bdefb-bc2a-452f-b815-a060f9cfeee7)

**Comment by Abid-Chowdhury** [comment]
- Add header to about page
- pick which colors to use for the page
