### ISSUE TITLE
Building Page Designs 

### ISSUE THREAD

**Issue by SininAssets** [Abid-Chowdhury/Habit-Quest#31]
working on page designs and making them operable.

**Comment by SininAssets** [comment]
![PreBetaDesign](https://github.com/Abid-Chowdhury/Habit-Quest/assets/144292292/df7f51bd-eb6f-4638-8432-45e652e6b054)

Just a suggestion for the shop, It will need more assets, will further develop upon approval

**Comment by Abid-Chowdhury** [comment]
I like it. simple and clean. Also could you please design the profile page? I'll get started right after the about page. And we need to discuss what items are gonna be in the shop and how the user will earn coin. Pretty much we gotta figure out the economy system of the app.

**Comment by SininAssets** [comment]
![Screenshot 2024-04-04 210458](https://github.com/Abid-Chowdhury/Habit-Quest/assets/144292292/4312f5cd-0630-49a3-994f-85941931654c)

Here is the selected page

**Comment by Abid-Chowdhury** [comment]
Sounds good to me
