### ISSUE TITLE
Add font

### ISSUE THREAD

**Issue by Abid-Chowdhury** [Abid-Chowdhury/Habit-Quest#6]

**Comment by Abid-Chowdhury** [comment]
1 Font for title
1 Font for everything else

**Comment by SininAssets** [comment]
![Screenshot 2024-03-22 125839](https://github.com/Abid-Chowdhury/Habit-Quest/assets/144292292/f4bcf7d2-8490-4a14-b959-6ac6a92b58ba)
Title Font: Rum raisin 
Regular Font: Inter-Regular
