### ISSUE TITLE
Need color codes for project

### ISSUE THREAD

**Issue by Abid-Chowdhury** [Abid-Chowdhury/Habit-Quest#9]
### **Need shades for these colors**
**_Format: name | hex | rgb_**

1. Black (dark gray / black / navy)
2. White (offwhite / light gray)
3. Red
4. Green
5. Blue

_Example: Black | #A9A9A9 | rgb(169, 169, 169)_

**Comment by SininAssets** [comment]
Black: 
Navy Black | #263032 | rgb(38, 48, 50)
Gun Metal | #2B303A | rgb(43, 48, 58 3)
Night | #131112,19 | rgb(17, 18 4)
??? | #0C0C14 | rgb(12, 12, 20)

White: 
Platinum | #EAEAEA | rgb(234, 234, 234) 
Ash Gray | #B3BFB8 | rgb(179, 191, 184)
Mint Cream | #F0F7F4 | rgb(240, 247, 244)
Ghost White | #F7F7FF | rgb(247, 247, 255)

Red:
Wine Red | #632B30 | rgb(99, 43, 48)
Rusty Red | #DE3C4B | rgb(222, 60, 75)
Penn Redd | #941B0C | rgb(148, 27, 12)
Imperial Red | #F93943 | rgb(249, 57, 67)

Green
Celadon | #9CDE9F | rgb(156, 222, 159)
Tea Green | #D1F5BE | rgb(209, 245, 190)
Apple Green | #7CB518 | rgb(124, 181, 24)
Avacado | #5C8001 | rgb(92, 128, 1)

Blue
UCLA Blue | #2274A5 | rgb(34, 116, 165)
Lapis Lazuli | #33658A | rgb(51, 101, 138)
Carolina Blue | #86BBD8 | rgb(134, 187, 216)
Celestial Blue | #279AF1 | rgb(39, 154, 241)

**Comment by Abid-Chowdhury** [comment]
**These are the color codes:**

```
/* Colors */
:root {
    --blackh: #0C0C14;
    --blackr: rgba(12, 12, 20, 255);

    --whiteh: #F0F7F4;
    --whiter: rgba(240, 247, 244, 255);

    --blueh: #279AF1;
    --bluer: rgba(39, 154, 241, 255);

    --redh: #F93943;
    --redr: rgba(249, 57, 67, 255);

    --greenh: #9CDE9F;
    --greenr: rgba(156, 222, 159, 255);
}
```
